### ISSUE TITLE
as a user I should see restricted number of symbols

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-gauzy-teams#452]
Since the App widgets have limited space/size, engineers should prevent any unpredictable size changes for all objects within the app.

For text/names within one object which are out of limit size should be added ' ... ' (that means that the name is longer)
For such cases in WEB, we use 'Tooltips' to display the full name/title, when the user hovers the object

For WEB we have 64 symbols max size, but for view, it is restricted.

We need to restrict:

- Team Names
- User Names
- User Email
- Task titles
- Task Description
- Status names
- Labels names
- Sizes names
- Priorities names

**Note:** We need to rely on an optimal/average number of symbols for different web page sizes

**Comment by paradoxe35** [comment]
Agree with you @badalkhatri0924 
This can be marked as complete
