### ISSUE TITLE
Email verification 

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-gauzy-teams#662]
1. Created a team
2. Joined account (the system sends a welcome email and verification email with code/link)
3. Clicked Verify (once users click 'Verify' should open pop with code input)

<img width="1299" alt="Screenshot at Mar 15 17-21-36" src="https://user-images.githubusercontent.com/107203576/225374453-000edc76-4c8c-4788-b708-5b547937e2f0.png">

4. No code on email - only button Verify (seems like the system knows that I already have account). 

<img width="1140" alt="Screenshot at Mar 15 17-17-43" src="https://user-images.githubusercontent.com/107203576/225374040-16517806-3deb-46a9-8b74-d88bf7902050.png">

<img width="832" alt="Screenshot at Mar 15 17-18-01" src="https://user-images.githubusercontent.com/107203576/225374026-da55a8ec-a5dd-4aa5-b548-e4abae3ca1f6.png">

**Comment by badalkhatri0924** [comment]
@KostyaEver This is working fine now. Let me know if you still face an issue.
