### ISSUE TITLE
Bug | Login email

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-gauzy-teams#783]
Flow: 
- user tries to Login 
- provide own email
- click 'Continue'
- check own email
- Two options: copy the code OR click on the link

Bug: the link in the email is NOT clickable

<img width="666" alt="Screenshot at Apr 14 09-24-57" src="https://user-images.githubusercontent.com/107203576/231975211-149f039d-54ac-43d3-b5e1-cb89f6a6d6c8.png">

**Comment by badalkhatri0924** [comment]
@KostyaEver This is working fine now. Please let me know if you still face an issue.
